service: example-api-2

provider: ${file(../../serverless.base.yml):provider}
plugins: ${file(../../serverless.base.yml):plugins}

custom:
  serverless-offline:
    httpPort: 3001
    lambdaPort: 4001
    reloadHandler: ${file(../../serverless.base.yml):custom.serverless-offline.reloadHandler}
  bundle: ${file(../../serverless.base.yml):custom.bundle}

functions:
  main:
    handler: src/handler.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
